### ISSUE TITLE
Adding Client to a 'project'

### ISSUE THREAD

**Issue by ChrisChinchilla** [crate/craterl#7]
Hey @mfelsche Could you add something to the docs about how you actually start using the client? i.e. add it to your project or application.

A step above `ok = craterl:start().`

Something like - https://github.com/basho/riak-erlang-client or http://basho.github.io/riak-erlang-client/

I have no ideas about Erlang so can't really start our own 'Getting Started' section without this step.

Thanks!

**Comment by mfelsche** [comment]
Does this makes sense to you? #8
Will add additional example apps to show some more usage examples
